timezone: Asia/Tokyo

caddy_custom_version: 2.5.2-4
cadvisor_version: v0.45.0
node_exporter_version: 1.3.1

cloudflare_api_key: "{{vault_cloudflare_api_key}}"

traq:
  port: 8000
  frontend_port: 8001
  widget_port: 8002
  webrtc:
    api_key: "{{vault_traq_webrtc_api_key}}"
    api_secret: "{{vault_traq_webrtc_api_secret}}"

db:
  traq:
    username: traq
    password: "{{vault_traq_password}}"
    root_password: "{{vault_traq_root_password}}"
    database: traq
    port: 3306

grafana:
  host: grafana.example.com
  client_id: "{{vault_grafana_client_id}}"
  client_secret: "{{vault_grafana_client_secret}}"

livekit:
  api_key: "{{vault_livekit_api_key}}"
  api_secret: "{{vault_livekit_api_secret}}"