- name: Download & unpack node_exporter binary to local folder
  become: false
  unarchive:
    remote_src: true
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Create /opt/node_exporter
  file:
    path: /opt/node_exporter
    state: directory
    mode: 0755

- name: Propagate node_exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
    dest: "/opt/node_exporter/node_exporter"
    mode: 0755
  notify: restart node_exporter
  check_mode: false

- name: Copy the Node Exporter systemd service file
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter

- name: Ensure Node Exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
