version: '2'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.26.0
    restart: always
    command: [
      "--config.file=/etc/prometheus/prometheus.yaml",
      "--storage.tsdb.path=/prometheus",
      "--storage.tsdb.retention=30d",
      "--web.console.libraries=/usr/share/prometheus/console_libraries",
      "--web.console.templates=/usr/share/prometheus/consoles",
      "--web.enable-lifecycle"
    ]
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus:/etc/prometheus
      - /opt/prometheus/data:/prometheus
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.4
    restart: always
    user: root
    ports:
      - "3000:3000"
    volumes:
      - /opt/grafana/data:/var/lib/grafana
      - /opt/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
  trickster:
    container_name: trickster
    image: tricksterio/trickster:1.1.5
    restart: always
    ports:
      - "9091:9091"
      - "8082:8082"
    volumes:
      - /opt/trickster/trickster.conf:/etc/trickster/trickster.conf:ro
  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter:v0.18.0
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - /opt/blackbox_exporter/blackbox.yaml:/etc/blackbox_exporter/config.yaml:ro
  ssl_exporter:
    container_name: ssl_exporter
    image: ribbybibby/ssl-exporter:v2.2.0
    restart: always
    ports:
      - "9219:9219"
  domain_exporter:
    container_name: domain_exporter
    image: caarlos0/domain_exporter:v1.10.0
    restart: always
    ports:
      - "9222:9222"