- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Install basic list of packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - python3-pip
      - curl
  become: true

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: true

- name: Install Docker packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  become: true

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: true
  become: true


- name: pip install docker
  pip:
    name:
      - docker
      - docker-compose
